import { StyleSheet } from "react-native";
import { ContainerStyles, HeaderStyles, Colors } from "../../styles/common.styles";

export default StyleSheet.create({
  container: ContainerStyles.base,
  scrollContent: {
    paddingTop: 20,
    paddingBottom: 100,
  },
  headerSection: {
    paddingHorizontal: 20,
  },
  headerContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  backButton: HeaderStyles.backButton,
  title: HeaderStyles.title,
  shareButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Colors.backgroundGray,
  },
  contentSection: {
    paddingHorizontal: 20,
    marginTop: 2,
  },
  detailsCard: {
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 8,
    marginBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderGray,
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 6,
    borderBottomColor: Colors.backgroundGray,
  },
  detailLabelContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  detailLabel: {
    fontSize: 14,
    fontWeight: "500",
    color: Colors.textTertiary,
  },
  detailValue: {
    fontSize: 14,
    fontWeight: "400",
    color: Colors.textSecondary,
    flex: 1,
    textAlign: "right",
  },
  typeTag: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: Colors.backgroundGray,
    borderRadius: 6,
  },
  typeText: {
    fontSize: 13,
    fontWeight: "500",
    color: Colors.textTertiary,
  },
  githubSection: {
    borderRadius: 12,
    paddingVertical: 12,
  },
  githubButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 12,
    paddingHorizontal: 12,
    width: "100%",
    backgroundColor: Colors.dark,
    borderRadius: 8,
    alignSelf: "flex-start",
  },
  githubButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: Colors.textWhite,
  },
  usersSection: {
    borderRadius: 12,
    paddingVertical: 20,
    paddingHorizontal: 12,
    marginBottom: 16,
  },
  usersTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: Colors.textSecondary,
    marginBottom: 16,
  },
  userCard: {
    backgroundColor: Colors.backgroundWhite,
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: Colors.borderGray,
  },
  userHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 12,
  },
  userAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.primary,
    justifyContent: "center",
    alignItems: "center",
  },
  userAvatarText: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.textWhite,
  },
  userInfo: {
    flex: 1,
  },
  userName: {
    fontSize: 15,
    fontWeight: "600",
    color: Colors.textSecondary,
    marginBottom: 2,
  },
  userUsername: {
    fontSize: 13,
    fontWeight: "400",
    color: Colors.textGray,
  },
  userDetails: {
    gap: 8,
  },
  userDetailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  userDetailLabel: {
    fontSize: 13,
    fontWeight: "500",
    color: Colors.textGray,
  },
  userDetailValue: {
    fontSize: 13,
    fontWeight: "400",
    color: Colors.textSecondary,
  },
  userDescription: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: Colors.backgroundGray,
  },
  userDescriptionText: {
    fontSize: 13,
    fontWeight: "400",
    color: Colors.textTertiary,
    lineHeight: 18,
  },
  loadingContainer: ContainerStyles.loading,
  errorContainer: ContainerStyles.error,
  errorText: {
    fontSize: 16,
    fontWeight: "600",
    color: Colors.error,
    textAlign: "center",
    marginBottom: 8,
  },
  errorSubtext: {
    fontSize: 14,
    color: Colors.textGray,
    textAlign: "center",
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: Colors.textSecondary,
    marginBottom: 16,
  },
  githubIssueSection: {
    borderRadius: 16,
    paddingVertical: 20,
  },
  githubIssueCard: {
    backgroundColor: Colors.backgroundWhite,
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: Colors.borderGray,
  },
  githubIssueBody: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: Colors.backgroundGray,
  },
  githubIssueBodyText: {
    fontSize: 13,
    fontWeight: "400",
    color: Colors.textTertiary,
    lineHeight: 18,
  },
  labelsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    flex: 1,
    justifyContent: "flex-end",
  },
  labelTag: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    borderWidth: 1,
  },
  labelText: {
    fontSize: 11,
    fontWeight: "500",
  },
  loadingText: {
    fontSize: 14,
    color: Colors.textGray,
    textAlign: "center",
    paddingVertical: 12,
  },
});
