import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F9FAFB",
  },
  scrollContent: {
    paddingBottom: 20,
  },
  headerSection: {
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  headerContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#E5E7EB",
  },
  titleContainer: {
    flex: 1,
  },
  titleLine: {
    height: 24,
    width: "85%",
    marginBottom: 8,
    borderRadius: 4,
    backgroundColor: "#E5E7EB",
  },
  titleLineShort: {
    height: 24,
    width: "60%",
    borderRadius: 4,
    backgroundColor: "#E5E7EB",
  },
  shareButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#E5E7EB",
  },
  contentSection: {
    paddingHorizontal: 20,
  },
  detailsCard: {
    borderRadius: 12,
    paddingVertical: 20,
    paddingHorizontal: 12,
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
    backgroundColor: "#FFFFFF",
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
    borderBottomColor: "#F3F4F6",
    borderBottomWidth: 1,
    marginBottom: 8,
  },
  detailLabelContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  iconPlaceholder: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: "#E5E7EB",
  },
  labelLine: {
    height: 16,
    width: 70,
    borderRadius: 4,
    backgroundColor: "#E5E7EB",
  },
  valueLine: {
    height: 16,
    width: 120,
    borderRadius: 4,
    backgroundColor: "#E5E7EB",
  },
  assigneeContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
    justifyContent: "flex-end",
  },
  assigneeAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#E5E7EB",
  },
  assigneeLine: {
    height: 16,
    width: 100,
    borderRadius: 4,
    backgroundColor: "#E5E7EB",
  },
  statusBadge: {
    width: 80,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#E5E7EB",
  },
  priorityTag: {
    width: 90,
    height: 32,
    borderRadius: 6,
    backgroundColor: "#E5E7EB",
  },
  typeTag: {
    width: 80,
    height: 32,
    borderRadius: 6,
    backgroundColor: "#E5E7EB",
  },
  progressCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    paddingVertical: 20,
    paddingHorizontal: 12,
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  progressHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  progressLabelLine: {
    height: 16,
    width: 70,
    borderRadius: 4,
    backgroundColor: "#E5E7EB",
  },
  progressPercentageLine: {
    height: 16,
    width: 50,
    borderRadius: 4,
    backgroundColor: "#E5E7EB",
  },
  progressBar: {
    height: 6,
    backgroundColor: "#F3F4F6",
    borderRadius: 3,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    width: "60%",
    backgroundColor: "#E5E7EB",
    borderRadius: 3,
  },
  githubSection: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    paddingVertical: 20,
    paddingHorizontal: 12,
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  githubButton: {
    height: 44,
    width: "100%",
    borderRadius: 8,
    backgroundColor: "#E5E7EB",
  },
  dependenciesSection: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    paddingVertical: 20,
    paddingHorizontal: 12,
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  dependenciesTitleLine: {
    height: 18,
    width: 120,
    borderRadius: 4,
    backgroundColor: "#E5E7EB",
    marginBottom: 12,
  },
  dependencyItem: {
    height: 40,
    borderRadius: 6,
    backgroundColor: "#F9FAFB",
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  progressAccordionSection: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    paddingVertical: 20,
    paddingHorizontal: 12,
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  accordionTitleLine: {
    height: 18,
    width: 100,
    borderRadius: 4,
    backgroundColor: "#E5E7EB",
    marginBottom: 12,
  },
  accordionItem: {
    height: 60,
    borderRadius: 6,
    backgroundColor: "#F9FAFB",
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  skeletonLine: {
    borderRadius: 4,
    backgroundColor: "#E5E7EB",
  },
});
