import { StyleSheet } from "react-native";
import { ContainerStyles, HeaderStyles, ProgressStyles, Colors } from "../../styles/common.styles";

export default StyleSheet.create({
  container: ContainerStyles.base,
  scrollContent: ContainerStyles.scrollContent,
  headerSection: {
    paddingHorizontal: 20,
  },
  headerContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  backButton: HeaderStyles.backButton,
  title: HeaderStyles.title,
  shareButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Colors.backgroundGray,
  },
  contentSection: {
    paddingHorizontal: 20,
    marginTop: 2,
  },
  detailsCard: {
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 8,
    marginBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderGray,
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 6,
    borderBottomColor: Colors.backgroundGray,
  },
  detailLabelContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  detailLabel: {
    fontSize: 14,
    fontWeight: "500",
    color: Colors.textTertiary,
  },
  detailValue: {
    fontSize: 14,
    fontWeight: "400",
    color: Colors.textSecondary,
    flex: 1,
    textAlign: "right",
  },
  assigneeContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
    justifyContent: "flex-end",
  },
  assigneeAvatar: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: Colors.primary,
    justifyContent: "center",
    alignItems: "center",
  },
  assigneeAvatarText: {
    fontSize: 12,
    fontWeight: "700",
    color: Colors.textWhite,
  },
  assigneeName: {
    fontSize: 14,
    fontWeight: "400",
    color: Colors.textSecondary,
  },
  priorityTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    borderWidth: 1,
  },
  priorityDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  priorityText: {
    fontSize: 13,
    fontWeight: "500",
  },
  typeTag: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: Colors.backgroundGray,
    borderRadius: 6,
  },
  typeText: {
    fontSize: 13,
    fontWeight: "500",
    color: Colors.textTertiary,
  },
  progressCard: {
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 12,
    marginTop: 16,
    marginHorizontal: 20,
  },
  progressHeader: {
    ...ProgressStyles.header,
    marginBottom: 12,
  },
  progressLabel: {
    fontSize: 15,
    fontWeight: "600",
    color: Colors.textSecondary,
  },
  progressPercentage: {
    fontSize: 15,
    fontWeight: "600",
    color: Colors.primary,
  },
  progressBar: {
    ...ProgressStyles.bar,
    backgroundColor: Colors.backgroundGray,
  },
  progressFill: {
    ...ProgressStyles.fill,
    borderRadius: 4,
  },
  githubSection: {
    borderRadius: 12,
    paddingVertical: 12,
    marginBottom: 16,
  },
  githubButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 12,
    paddingHorizontal: 12,
    width: "100%",
    backgroundColor: Colors.dark,
    borderRadius: 8,
    alignSelf: "flex-start",
  },
  githubButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: Colors.textWhite,
  },
  dependenciesSection: {
    borderRadius: 12,
    paddingVertical: 20,
    paddingHorizontal: 12,
  },
  dependenciesTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: Colors.textSecondary,
    marginBottom: 12,
  },
  dependencyItem: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: Colors.background,
    borderRadius: 6,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: Colors.borderGray,
  },
  dependencyText: {
    fontSize: 13,
    fontWeight: "500",
    color: Colors.textGray,
  },
  emptyDependencies: {
    fontSize: 12,
    color: Colors.textLight,
    fontStyle: "italic",
  },
  loadingContainer: ContainerStyles.loading,
  errorContainer: ContainerStyles.error,
  errorText: {
    fontSize: 16,
    fontWeight: "600",
    color: Colors.error,
    textAlign: "center",
    marginBottom: 8,
  },
  errorSubtext: {
    fontSize: 14,
    color: Colors.textGray,
    textAlign: "center",
  },
});
