import { StyleSheet } from "react-native";
import { AvatarStyles, Colors, ContainerStyles, Typography } from "../../styles/common.styles";

export default StyleSheet.create({
  container: ContainerStyles.base,
  scrollContent: ContainerStyles.scrollContent,
  headerSection: {
    alignItems: "center",
    paddingTop: 40,
    paddingBottom: 32,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    marginBottom: 8,
    overflow: "hidden",
  },
  avatarContainer: {
    position: "relative",
  },
  avatar: AvatarStyles.large,
  avatarPlaceholder: {
    ...AvatarStyles.large,
    backgroundColor: Colors.primary,
  },
  avatarPlaceholderText: AvatarStyles.textLarge,
  fullName: {
    ...Typography.h1,
    marginBottom: 6,
    textAlign: "center",
  },
  username: {
    fontSize: 16,
    fontWeight: "500",
    color: Colors.textGray,
    textAlign: "center",
  },
  section: {
    backgroundColor: "transparent",
    marginTop: 20,
    paddingHorizontal: 20,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.textPrimary,
    marginBottom: 12,
    marginLeft: 4,
    letterSpacing: 0.3,
  },
  card: {
    backgroundColor: Colors.backgroundWhite,
    borderRadius: 16,
    padding: 20,
    marginBottom: 0,
    borderWidth: 0,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: Colors.backgroundGray,
  },
  infoRowLast: {
    marginBottom: 0,
    paddingBottom: 0,
    borderBottomWidth: 0,
  },
  infoLabelContainer: {
    flexDirection: "row",
    alignItems: "center",
    minWidth: 120,
    marginRight: 16,
  },
  infoLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.textGray,
    marginLeft: 8,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  infoValue: {
    fontSize: 15,
    fontWeight: "500",
    color: Colors.textPrimary,
    flex: 1,
  },
  iconContainer: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: Colors.borderLight,
    justifyContent: "center",
    alignItems: "center",
  },
  rolesContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  roleBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: Colors.backgroundGray,
    borderWidth: 1,
    borderColor: Colors.borderGray,
  },
  roleBadgeText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#4B5563",
    letterSpacing: 0.2,
  },
  socialLinksContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  socialLink: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: Colors.background,
    borderWidth: 1,
    borderColor: Colors.borderGray,
    flex: 1,
    minWidth: "47%",
  },
  socialLinkText: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.textPrimary,
    marginLeft: 8,
  },
  logoutButton: {
    flexDirection: "row",
    backgroundColor: "#FEF2F2",
    marginHorizontal: 20,
    marginTop: 32,
    paddingVertical: 18,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  logoutButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.error,
    letterSpacing: 0.5,
    marginLeft: 10,
  },
  loadingContainer: {
    ...ContainerStyles.loading,
    backgroundColor: Colors.backgroundWhite,
  },
  loadingText: {
    fontSize: 16,
    color: Colors.textGray,
    marginTop: 12,
  },
  errorContainer: {
    ...ContainerStyles.error,
    backgroundColor: Colors.backgroundWhite,
  },
  errorText: {
    fontSize: 16,
    fontWeight: "600",
    color: Colors.error,
    textAlign: "center",
  },
  emptyValue: {
    fontSize: 14,
    fontWeight: "400",
    color: Colors.textLight,
    fontStyle: "italic",
  },
});
